using System.Windows;
using System.Windows.Controls;
using Lonnii.Shared.Contracts;

namespace Lonnii.Client.Views.Dialogs;

/// <summary>Creates or edits a charge, including its recurring settings. Recurrence is only
/// offered for a <c>fixe</c> charge that is not itself an occurrence generated by another
/// recurring charge - the server rejects anything else, so this dialog never lets the user
/// reach that state instead of showing a refusal after the fact.</summary>
public partial class ChargeDialog : Window
{
    private readonly ChargeDto? _existing;

    public SaveChargeRequest? Result { get; private set; }

    public ChargeDialog(ChargeDto? existing, IReadOnlyList<ChargeCategoryDto> categories)
    {
        _existing = existing;
        InitializeComponent();

        // Wired here rather than in XAML: a XAML-declared handler is connected as soon as
        // this element is built (TypeCombo has an IsSelected="True" item), which fires it
        // immediately during InitializeComponent - while RecurringCheck, declared later in
        // the tree, does not exist yet, crashing ApplyRecurringEnabled(). Same fix as
        // VentesView's RemiseGlobaleBox.
        TypeCombo.SelectionChanged += (_, _) => ApplyRecurringEnabled();

        // Grouped ("1 000,25") only once typing is done, same as VentesView's cart price
        // boxes - reformatting every keystroke would fight the caret position and the space
        // the user is trying to type past.
        MontantBox.LostFocus += (_, _) =>
        {
            if (Money.TryParse(MontantBox.Text, out decimal montant))
                MontantBox.Text = Money.FormatPlain(montant);
        };

        CategorieCombo.ItemsSource = categories;

        if (existing is null)
        {
            HeaderText.Text = "Nouvelle charge";
            HeaderHint.Text = "Enregistrez une nouvelle dépense.";
            DatePicker.SelectedDate = DateTime.Today;
            MontantBox.Text = "0";
        }
        else
        {
            HeaderText.Text = "Modifier la charge";
            HeaderHint.Text = existing.Description;

            DescriptionBox.Text = existing.Description;
            MontantBox.Text = Money.FormatPlain(existing.Montant);
            DatePicker.SelectedDate = existing.Date;

            foreach (ComboBoxItem item in TypeCombo.Items)
                if ((string)item.Tag == existing.TypeCharge) { TypeCombo.SelectedItem = item; break; }

            CategorieCombo.SelectedItem = categories.FirstOrDefault(c => c.Nom == existing.Categorie);

            if (existing.RecurringSourceId is not null)
            {
                // A generated occurrence: recurrence is entirely the source charge's concern.
                RecurringCheck.IsEnabled = false;
                RecurringCheck.ToolTip = "Cette charge a été créée automatiquement; sa récurrence se gère sur la charge source.";
                GeneratedNotice.Visibility = Visibility.Visible;
            }
            else if (existing.IsRecurring)
            {
                RecurringCheck.IsChecked = true;
                RecurringEndPicker.SelectedDate = existing.RecurringEndDate;
                if (existing.RecurringDay is "debut" or "fin")
                {
                    foreach (ComboBoxItem item in RecurringDayCombo.Items)
                        if ((string)item.Tag == existing.RecurringDay) { RecurringDayCombo.SelectedItem = item; break; }
                }
                else if (existing.RecurringDay is { } day)
                {
                    RecurringDayBox.Text = day;
                }
            }
        }

        ApplyRecurringEnabled();
        Loaded += (_, _) => { DescriptionBox.Focus(); DescriptionBox.SelectAll(); };
    }

    private void RecurringCheck_Changed(object sender, RoutedEventArgs e) =>
        RecurringPanel.Visibility = RecurringCheck.IsChecked == true ? Visibility.Visible : Visibility.Collapsed;

    /// <summary>Recurrence only makes sense for a "fixe" charge - unchecking and hiding it
    /// the moment "Variable" is picked, same as the source app's own form.</summary>
    private void ApplyRecurringEnabled()
    {
        var isFixe = (TypeCombo.SelectedItem as ComboBoxItem)?.Tag as string == "fixe";
        var canRecur = isFixe && _existing?.RecurringSourceId is null;

        RecurringCheck.IsEnabled = canRecur;
        if (!canRecur && _existing?.RecurringSourceId is null) RecurringCheck.IsChecked = false;
    }

    private void Save_Click(object sender, RoutedEventArgs e)
    {
        var description = DescriptionBox.Text.Trim();
        if (string.IsNullOrWhiteSpace(description))
        {
            ErrorText.Text = "La description est requise.";
            DescriptionBox.Focus();
            return;
        }

        if (!Money.TryParse(MontantBox.Text, out decimal montant) || montant <= 0)
        {
            ErrorText.Text = "Indiquez un montant valide.";
            MontantBox.Focus();
            return;
        }

        if (CategorieCombo.SelectedItem is not ChargeCategoryDto categorie)
        {
            ErrorText.Text = "Choisissez une catégorie.";
            CategorieCombo.Focus();
            return;
        }

        if (DatePicker.SelectedDate is not { } date)
        {
            ErrorText.Text = "La date est requise.";
            DatePicker.Focus();
            return;
        }

        var typeCharge = (string)((ComboBoxItem)TypeCombo.SelectedItem).Tag;
        var isRecurring = RecurringCheck.IsChecked == true;

        DateTime? recurringEndDate = null;
        string? recurringDay = null;

        if (isRecurring)
        {
            if (RecurringEndPicker.SelectedDate is not { } end)
            {
                ErrorText.Text = "Indiquez jusqu'à quand cette charge doit être recréée chaque mois.";
                RecurringEndPicker.Focus();
                return;
            }

            var chargeMonthEnd = new DateTime(date.Year, date.Month, 1).AddMonths(1).AddDays(-1);
            if (end.Date <= chargeMonthEnd)
            {
                ErrorText.Text = "La date de fin doit couvrir au moins le mois suivant.";
                RecurringEndPicker.Focus();
                return;
            }

            recurringEndDate = end;
            recurringDay = string.IsNullOrWhiteSpace(RecurringDayBox.Text)
                ? (string)((ComboBoxItem)RecurringDayCombo.SelectedItem).Tag
                : RecurringDayBox.Text.Trim();
        }

        Result = new SaveChargeRequest(
            description, montant, typeCharge, categorie.Nom, date, isRecurring, recurringEndDate, recurringDay);
        DialogResult = true;
    }
}
