// <auto-generated />
using System;
using Lonnii.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lonnii.Data.Migrations
{
    [DbContext(typeof(LonniiDbContext))]
    [Migration("20260924132301_AddDevicesAndGroupIsDeleted")]
    partial class AddDevicesAndGroupIsDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Lonnii.Data.Entities.Caisse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateFermeture")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_fermeture");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_ouverture");

                    b.Property<long>("Ecart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ecart");

                    b.Property<string>("EcartResolutionNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("ecart_resolution_note");

                    b.Property<bool>("EcartResolved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ecart_resolved");

                    b.Property<DateTime?>("EcartResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ecart_resolved_at");

                    b.Property<string>("EcartResolvedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("ecart_resolved_by");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<long?>("MontantFinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("montant_final");

                    b.Property<long>("MontantInitial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("montant_initial");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("PaiementAutres")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paiement_autres");

                    b.Property<long>("PaiementCarte")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paiement_carte");

                    b.Property<long>("PaiementCash")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paiement_cash");

                    b.Property<long>("PaiementMobile")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paiement_mobile");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("TotalAvoir")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_avoir");

                    b.Property<long>("TotalChiffreAffaires")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_chiffre_affaires");

                    b.Property<long>("TotalEncaisse")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_encaisse");

                    b.Property<long>("TotalRestant")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_restant");

                    b.Property<int>("TotalVentes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_ventes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Status");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasFilter("status = 'open'");

                    b.ToTable("caisses");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.CaisseTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CaisseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("caisse_id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("ModePaiement")
                        .HasColumnType("TEXT")
                        .HasColumnName("mode_paiement");

                    b.Property<long>("Montant")
                        .HasColumnType("INTEGER")
                        .HasColumnName("montant");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CaisseId");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("caisse_transactions");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT")
                        .HasColumnName("telephone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.DashboardSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AdminId")
                        .HasColumnType("TEXT")
                        .HasColumnName("admin_id");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("admin_name");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_date");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("contract_end_date");

                    b.Property<string>("ContractPdfFilename")
                        .HasColumnType("TEXT")
                        .HasColumnName("contract_pdf_filename");

                    b.Property<string>("ContractPdfUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("contract_pdf_url");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("contract_start_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DateVente")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_vente");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_name");

                    b.Property<long>("Montant")
                        .HasColumnType("INTEGER")
                        .HasColumnName("montant");

                    b.Property<long?>("MontantPreabonnement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("montant_preabonnement");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("statut");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Statut");

                    b.HasIndex("GroupId", "ContractEndDate");

                    b.ToTable("dashboard_subscriptions");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_version");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("LastIpAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_ip_address");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("registered_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_reason");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupId", "DeviceId")
                        .IsUnique();

                    b.ToTable("devices");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GestionPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin_only");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Module");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("gestion_privileges");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GestionPrivilegeAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("Module")
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("performed_by");

                    b.Property<int?>("PrivilegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privilege_id");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RoleFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_from");

                    b.Property<string>("RoleTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_to");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_user_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Module");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("gestion_privilege_audit");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GestionUserPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_by");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privilege_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("UserId", "GroupId", "PrivilegeId")
                        .IsUnique();

                    b.ToTable("gestion_user_privileges");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GestionUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_by");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GroupId", "Module")
                        .IsUnique();

                    b.ToTable("gestion_user_roles");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GroupMember", b =>
                {
                    b.Property<string>("IdGroupe")
                        .HasColumnType("TEXT")
                        .HasColumnName("idgroupe");

                    b.Property<string>("IdUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("iduser");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("joined_at");

                    b.HasKey("IdGroupe", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("groupe_membres");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Groupe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BlockReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("block_reason");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("blocked_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyLabel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_label");

                    b.Property<bool>("GestionAccess")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gestion_access");

                    b.Property<string>("IdUserAdmin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iduser_admin");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxDevices")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_devices");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom");

                    b.Property<bool>("PrestationsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prestations_access");

                    b.Property<string>("PrestationsLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("prestations_location");

                    b.HasKey("Id");

                    b.HasIndex("IdUserAdmin");

                    b.ToTable("groupes");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GroupeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_accessed_at");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("groupe_sessions");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.OptionPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin_only");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Module");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("option_privileges");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.OptionPrivilegeAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("Module")
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("performed_by");

                    b.Property<int?>("PrivilegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privilege_id");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_user_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("option_privilege_audit");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.OptionUserPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_by");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privilege_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("UserId", "GroupId", "PrivilegeId")
                        .IsUnique();

                    b.ToTable("option_user_privileges");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.PaiementVente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_paiement");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode_paiement");

                    b.Property<long>("Montant")
                        .HasColumnType("INTEGER")
                        .HasColumnName("montant");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.Property<string>("VenteId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vente_id");

                    b.HasKey("Id");

                    b.HasIndex("VenteId");

                    b.ToTable("paiements_ventes");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iduser");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("password_history");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Privilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin_only");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("privileges");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.PrivilegeAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("performed_by");

                    b.Property<int?>("PrivilegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privilege_id");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RoleFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_from");

                    b.Property<string>("RoleTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_to");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_user_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("privilege_audit");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<long?>("CostPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long?>("DimensionsHeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimensions_height");

                    b.Property<long?>("DimensionsLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimensions_length");

                    b.Property<long?>("DimensionsWidth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimensions_width");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry_date");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsPerishable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_perishable");

                    b.Property<long?>("MarginPercentage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_percentage");

                    b.Property<int?>("MaximumThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maximum_threshold");

                    b.Property<int>("MinimumThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minimum_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price");

                    b.Property<bool>("PrixFixe")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prix_fixe");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int?>("ReorderQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reorder_quantity");

                    b.Property<bool>("RequiresSerialNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_serial_number");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shelf_life_days");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<bool>("StockIllimite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_illimite");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_location");

                    b.Property<string>("SupplierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("UniteAffichage")
                        .HasColumnType("TEXT")
                        .HasColumnName("unite_affichage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<bool>("VenteLibre")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vente_libre");

                    b.Property<long?>("Weight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("GroupId", "Barcode")
                        .IsUnique()
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("GroupId", "Sku")
                        .IsUnique()
                        .HasFilter("sku IS NOT NULL");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.RolePrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privilege_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("Role", "PrivilegeId")
                        .IsUnique();

                    b.ToTable("role_privileges");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.StockHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("movement_type");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_quantity");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_quantity");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityChanged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_changed");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_type");

                    b.Property<long?>("TotalCost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_cost");

                    b.Property<long?>("UnitCost")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_cost");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("stock_history");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.StockSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_public");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_name");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_type");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "SettingName")
                        .IsUnique();

                    b.ToTable("stock_settings");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.StockUserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("stock_user_activity");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_person");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_terms");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.User", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("TEXT")
                        .HasColumnName("iduser");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Poste")
                        .HasColumnType("TEXT")
                        .HasColumnName("poste");

                    b.Property<string>("ResetCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_code");

                    b.Property<DateTime?>("ResetCodeCreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_code_created_at");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.UserPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_by");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("PrivilegeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privilege_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeId");

                    b.HasIndex("UserId", "GroupId", "PrivilegeId")
                        .IsUnique();

                    b.ToTable("user_privileges");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LoginSource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login_source");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Vente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AvoirSoldedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("avoir_solded_at");

                    b.Property<int?>("CaisseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("caisse_id");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_email");

                    b.Property<string>("ClientNom")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_name");

                    b.Property<string>("ClientTelephone")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("DateVente")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsAvoirSolded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_avoir_solded");

                    b.Property<string>("ModePaiement")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.Property<long>("MontantTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("NumeroVente")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_number");

                    b.Property<string>("StatutPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("StatutPaiement");

                    b.HasIndex("GroupId", "DateVente");

                    b.HasIndex("GroupId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("GroupId", "NumeroVente")
                        .IsUnique();

                    b.ToTable("ventes");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.VenteItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("Discount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_type");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nom_produit");

                    b.Property<long>("PrixTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prix_total");

                    b.Property<long>("PrixUnitaire")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prix_unitaire");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantite");

                    b.Property<string>("VenteId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vente_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VenteId");

                    b.ToTable("ventes_items");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.VentesParametres", b =>
                {
                    b.Property<string>("GroupeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("groupe_id");

                    b.Property<string>("AvoirNoticeText")
                        .HasColumnType("TEXT")
                        .HasColumnName("avoir_notice_text");

                    b.Property<string>("AvoirNoticeTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("avoir_notice_title");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("company_name");

                    b.Property<string>("DocumentSignatory")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_signatory");

                    b.Property<string>("FactureFooterText")
                        .HasColumnType("TEXT")
                        .HasColumnName("facture_footer_text");

                    b.Property<string>("FactureHeaderText")
                        .HasColumnType("TEXT")
                        .HasColumnName("facture_header_text");

                    b.Property<string>("FactureTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("facture_title");

                    b.Property<string>("FontFamily")
                        .HasColumnType("TEXT")
                        .HasColumnName("font_family");

                    b.Property<int?>("FontSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("font_size");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_path");

                    b.Property<string>("NoteUnderQr")
                        .HasColumnType("TEXT")
                        .HasColumnName("note_under_qr");

                    b.Property<string>("QrCodePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("qr_code_path");

                    b.Property<string>("ReceiptFooterText")
                        .HasColumnType("TEXT")
                        .HasColumnName("receipt_footer_text");

                    b.Property<bool>("ShowDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_date");

                    b.Property<bool>("ShowDocumentSignatory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_document_signatory");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("GroupeId");

                    b.ToTable("ventes_parametres");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.VentesUserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("ventes_user_activity");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.CaisseTransaction", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Caisse", "Caisse")
                        .WithMany()
                        .HasForeignKey("CaisseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caisse");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Category", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Device", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GestionUserPrivilege", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.GestionPrivilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.GroupMember", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Groupe", "Groupe")
                        .WithMany("Members")
                        .HasForeignKey("IdGroupe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lonnii.Data.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Groupe", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("IdUserAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.OptionUserPrivilege", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.OptionPrivilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.PaiementVente", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Vente", "Vente")
                        .WithMany("Paiements")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Product", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lonnii.Data.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.RolePrivilege", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.StockHistory", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.UserPrivilege", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Privilege");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.VenteItem", b =>
                {
                    b.HasOne("Lonnii.Data.Entities.Vente", "Vente")
                        .WithMany("Items")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Groupe", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Lonnii.Data.Entities.Vente", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Paiements");
                });
#pragma warning restore 612, 618
        }
    }
}
