-- ============================================================================
-- Lonnii Desktop - additive columns on the live PostgreSQL database
--
-- Run by hand, after reading it. Never generated by EF: the migrations in
-- Lonnii.Data were authored against SQLite and would create money columns as
-- INTEGER where this database correctly has NUMERIC(15,2).
--
-- Safety properties of this script, which every future one here must keep:
--   * additive only - ADD COLUMN, never RENAME, DROP or ALTER TYPE
--   * every column nullable or carrying a DEFAULT, so existing rows stay valid
--   * IF NOT EXISTS throughout, so re-running it changes nothing
--   * wrapped in a transaction, so a failure half way leaves no partial change
--
-- Lonnii Business keeps working unchanged: it names its columns explicitly and
-- never sees these. Verified against the live schema of groupes on 2026-09-24.
-- ============================================================================

BEGIN;

-- How this workspace is deployed. Decides whether a subscription is checked at
-- all: local-mode shops run on their own hardware and are never billed.
-- Defaults to local so every existing workspace keeps working untouched - an
-- online default would demand a subscription none of them have.
ALTER TABLE groupes ADD COLUMN IF NOT EXISTS mode VARCHAR(20) NOT NULL DEFAULT 'local';

-- How many machines this shop may bind at once. Set per customer from the
-- dashboard; delivered to the installation when it activates.
-- 3 rather than 0: zero would read as "no machines allowed" and lock every
-- existing workspace out the moment the check goes live.
ALTER TABLE groupes ADD COLUMN IF NOT EXISTS max_devices INTEGER NOT NULL DEFAULT 3;

-- The label printed after every amount in this workspace. On the group rather
-- than the client so every till in the shop agrees.
ALTER TABLE groupes ADD COLUMN IF NOT EXISTS currency_label VARCHAR(16) NOT NULL DEFAULT 'FCFA';

-- Where the Prestations module appears: gestion, espace or both.
-- Nullable: null means "not configured", which is the correct state for every
-- existing row. Note the matching on/off flag is the existing prestations_access
-- column - this script deliberately does not add a second one.
ALTER TABLE groupes ADD COLUMN IF NOT EXISTS prestations_location VARCHAR(20);

COMMIT;

-- Check afterwards:
--   SELECT column_name, data_type, is_nullable, column_default
--   FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'groupes'
--   ORDER BY ordinal_position;
