-- ============================================================================
-- Lonnii Desktop - Programme (work schedule, announcements) and Comptabilité settings
--
-- Three whole tables the live database does not have (found by comparing the model with
-- information_schema, 2026-10-08). Lonnii Business has no such tables, so nothing it reads is
-- touched. The Audit attendance screen joins programme_entries, and the Bilan reads
-- comptabilite_parametres, so both failed with "relation does not exist" until now.
--
-- Same rules as the earlier scripts: IF NOT EXISTS, in a transaction. The API's own login
-- (lonnii_api) cannot create tables, so it is granted access here.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS comptabilite_parametres (
    group_id text NOT NULL,
    calcul_automatique boolean NOT NULL DEFAULT true,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_comptabilite_parametres" PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS programme_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    group_id text NOT NULL,
    user_id text NOT NULL,
    date timestamp with time zone NOT NULL,
    type text NOT NULL,
    heure_debut interval,
    heure_fin interval,
    note text,
    created_by text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_programme_entries" PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "IX_programme_entries_group_id_date" ON programme_entries (group_id, date);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_programme_entries_group_id_user_id_date" ON programme_entries (group_id, user_id, date);

CREATE TABLE IF NOT EXISTS programme_announcements (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    group_id text NOT NULL,
    user_id text,
    titre text NOT NULL,
    message text NOT NULL,
    date timestamp with time zone NOT NULL,
    created_by text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_programme_announcements" PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "IX_programme_announcements_group_id_date" ON programme_announcements (group_id, date);
CREATE INDEX IF NOT EXISTS "IX_programme_announcements_group_id_user_id_date" ON programme_announcements (group_id, user_id, date);

-- The API's login only reads and writes rows; give it the new tables (and their id sequences).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lonnii_api') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON comptabilite_parametres, programme_entries, programme_announcements TO lonnii_api;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO lonnii_api;
    END IF;
END $$;

COMMIT;
